

```{r}
install.packages("htmltab")
library(htmltab)
install.packages("tidyr")
library(tidyr)
install.packages("stringr")
library(stringr)
install.packages("magrittr")
library(magrittr)
```

Base de datos #3
```{r}
library(readxl)
base3 <- read_excel("base3.xlsx")
```

```{r}
#elimino columnas que no sirven
base3[,c(4:30)]=NULL
base3[,c(5:13)]=NULL
base3[,c(1:2)]=NULL
#elimino filas que no sirven
base3=base3[-c(1:3), ]
base3=base3[-c(197:223), ]
```

```{r}
#cambio de nombre a un caso en particular
base3[85,1]="PROVINCIA CONSTITUCIONAL DEL CALLAO"
#cambio de nombre
names(base3)= c("Provincia", "ÍndiceDensidadEstado")
#quitar el espacio en Provincias
base3$Provincia= gsub('\\s','', base3$Provincia)
```

```{r}
str(base3)
#convertir a numérica
base3[,-1]=lapply(base3[,-1], as.numeric)
#para cuando se hagan los clusters
base3=na.omit(base3)
base3[!complete.cases(base3),]
```


Base de datos #4: 
```{r}
library(readxl)
base4 <- read_excel("base3.xlsx")
```

```{r}
#elimino columnas que no sirven
base4[,c(4:39)]=NULL
base4[,c(1:2)]=NULL
#elimino filas que no sirven
base4=base4[-c(1:3), ]
base4=base4[-c(197:223), ]
```

```{r}
#cambio de nombre a un caso en particular
base4[85,1]="PROVINCIA CONSTITUCIONAL DEL CALLAO"
#cambio de nombre
#devengado actividad+inversión
names(base4)= c("Provincia", "DevengadoTotal")
#quitar el espacio en Provincias
base4$Provincia= gsub('\\s','', base4$Provincia)
```

```{r}
str(base4)
#convertir a numérica
base4[,-1]=lapply(base4[,-1], as.numeric)
#para cuando se hagan los clusters
base4=na.omit(base4)
base4[!complete.cases(base4),]
```
